### ISSUE TITLE
Interceptor anchors for testing

### ISSUE THREAD

**Issue by sparshev** [cloudbees/groovy-cps#106]
During testing of the shared libraries it's really useful to be able to intercept the calls.

### Reason:
All the current implementations of the Jenkins Shared Libraries unit tests are quite useless - there are a number of issues impossible to test outside of actual workflow-cps-plugin. We have the next issue about that: [JENKINS-33925](https://issues.jenkins-ci.org/browse/JENKINS-33925).

**Comment by sparshev** [comment]
Added a sample realization #107 for `Invoker.methodCall`. That will be great, if someone can check - how this will work for the groovy-cps project and if this is the right way - to discuss it further.

**Comment by dwnusbaum** [comment]
Closing, follow [JENKINS-33925](https://issues.jenkins.io/browse/JENKINS-33925) instead.
