### ISSUE TITLE
CPS transformation should honor the return type signature

### ISSUE THREAD

**Issue by kohsuke** [cloudbees/groovy-cps#12]
CPS transformation ignores the declared return type of function, and always treat as if it is typed as `Object`.

This creates a behaviour difference between normal Groovy code vs CPS-transformed code.

```
int foo() { return "abc" }
foo();  // compiles fine but at runtime throws ClassCastException

void bar() { 42; }
x=bar(); // runs fine but assigns null
```

This should be relatively easy by having Continuation check the type of the value (or substitute it by null in case of `void` methods)

**Comment by dwnusbaum** [comment]
I noticed this while working on SECURITY-2824. I added a new test that demonstrates the issue: https://github.com/cloudbees/groovy-cps/blob/bd35d050bc18c357d22f311b87ca71e9b4d806ce/lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java#L1036

I am closing this issue. If anyone comes across this and cares about the behavior, feel free to file a new issue on https://issues.jenkins.io/ with the component set to `workflow-cps-plugin`, but note that unless you work on it yourself it is very unlikely to ever be fixed.
