### ISSUE TITLE
Strange behaviour when NonCPS method is calling a CPS method

### ISSUE THREAD

**Issue by pauxus** [cloudbees/groovy-cps#48]
I did not find the exact reason or circumstances for this to happen, but I managed to create a test case showing the behaviour:

```groovy
    @Test
    void nonCPSCallsCPSMethod() {
        evalCPS('''
            class Foo {
                int count
            
                @NonCPS
                static Foo create(int value) {
                    def aList = [5,6,7,8].collect { new Foo(count: it) }
                    return aList.find { it.matches(value) }
                }
                
                boolean matches(int value) {
                    count == value
                }
            }
            
            Foo.create(7)
        ''')
    }
```

This fails in the `evalCPS` test method. The CPS version returns a Boolean, while the NonCPS version correctly returns a Foo instance.

Of course, a NonCPS method calling a CPS method might be considered questionable, but in that case at least the compiliation and/or the execution should fail with a meaningful exception.

**Comment by jglick** [comment]
> a NonCPS method calling a CPS method might be considered questionable

It is in fact intrinsically impossible to support, at least in the general case (in this case `matches` might as well have been `@NonCPS` as well).

> at least the compiliation and/or the execution should fail with a meaningful exception

Yes; already tracked as [JENKINS-31314](https://issues.jenkins-ci.org/browse/JENKINS-31314), and cf. #9.
