### ISSUE TITLE
Generate CpsDefaultGroovyMethods

### ISSUE THREAD

**Issue by kohsuke** [cloudbees/groovy-cps#7]
It's silly to hand-code `CpsDefaultGroovyMethods` by manually doing CPS transformation.

It'd save me a lot of typing if I can apply `CpsTransformer` during the build process of groovy-cps itself. This way, all I need to do is to cut&paste method definitions from Groovy's `DefaultGroovyMethods` that has `Closure` in the signature.

**Comment by jglick** [comment]
Do not forget to add `DefaultGroovyStaticMethods`, and the things mentioned in `DgmConverter`—I only found a usage of `Closure` in `ProcessGroovyMethods`. None of these methods are likely to be whitelisted or ever used from Pipeline, but we may as well add them just in case.

**Comment by jglick** [comment]
Done in #56.
