### ISSUE TITLE
No way to limit recursion: with bugs, GroovyCPS will consume all memory

### ISSUE THREAD

**Issue by svanoort** [cloudbees/groovy-cps#76]
There's no way to limit the depth of recursive calls, it just consumes ever-increasing memory as the depth grows.  

The automatic conversion of field access to getter calls means that the following common lazy-loading pattern translates to an unbounded recursive call that will bring down a Jenkins master:

```
def something = null
def getSomething() {
  if (something == null) {
    return "someComplexComputationResult;"
  }
}
def stuff = getSomething();
```

We need a way to limit the depth of the recursion to prevent this scenario and handle appropriately (error out or at least pause execution and force the issue to be addressed).

**Comment by svanoort** [comment]
Consider adding listener hooks that can collect stats when we create/run blocks about how many we're running and how deeply they nest (or use the Envs for that).

**Comment by jglick** [comment]
> automatic conversion of field access to getter calls

This is supposed to be conditional—a field reference inside the same class is _not_ supposed to be translated to a getter. I have some tests proving that this works in various cases (previous critical bugs). If you have found some cases where that does not work, file JIRAs for them and fix them separately.

Of course there can still be true endless recursions in user code not caused by mistranslations.

**Comment by svanoort** [comment]
@jglick I'm happy to look into that as a second PR (it seemed wonky to me, but wasn't sure if it was just groovy being groovy), but as you note this will also protect against both that and user-induced endless recursions. 

Seems reasonable to do this, since it is ready to go and this issue is causing production outages, then work on fixing the field reference problem, no?  That gives us a defense in depth against issues.

**Comment by jglick** [comment]
I am just not sure which is the riskier change at this point.

**Comment by svanoort** [comment]
@jglick Well let me ask this way: do you see anything in this change that looks immediately problematic?  I an agree to hold off releasing this fully until we can do the second thing, but would like to be able to at least hand a SNAPSHOT-based workflow-cps build containing this to people whose production masters are impacted, as an interim measure.

**Comment by jglick** [comment]
I think I found the flaw in the code sample BTW (alluded to in the PR):

```groovy
def something = null
```

defines a local variable, _not_ a field, and Groovy methods are not closures (they cannot access lexically enclosing local variables). I bet

``` groovy
String something = null
```

or

``` groovy
@Field something = null
```

or even perhaps

``` groovy
something = null
```

would make it work as intended.

**Comment by svanoort** [comment]
Released and resolved now.
