### ISSUE TITLE
NonCPS should target `TYPE`

### ISSUE THREAD

**Issue by chrylis** [cloudbees/groovy-cps#87]
When writing support classes for pipeline plugins, it's very easy to accidentally forget to apply `@NonCPS` to a method and end up with weird errors. Like `@CompileStatic`, `@NonCPS` should also be applicable to a whole type to treat every method as non-CPS.

**Comment by dwnusbaum** [comment]
I am closing this, but I filed [JENKINS-70018](https://issues.jenkins.io/browse/JENKINS-70018) to track it against Pipeline: Groovy Plugin.
