### ISSUE TITLE
NonCPS should throw early error with CompileStatic

### ISSUE THREAD

**Issue by chrylis** [cloudbees/groovy-cps#88]
`@NonCPS` and `@CompileStatic` are not compatible (and possibly not `@TypeChecked`)--very weird errors start showing up if they're combined. If the `@NonCPS` processor finds that its method is affected by `@CompileStatic`, it should throw an error instead of trying to compile and producing unintuitive downstream errors.

**Comment by dwnusbaum** [comment]
I am closing this, but I filed [JENKINS-70018](https://issues.jenkins.io/browse/JENKINS-70018) to track it against Pipeline: Groovy Plugin.
