### ISSUE TITLE
CompileStatic only works on methods

### ISSUE THREAD

**Issue by crichmond1989** [cloudbees/groovy-cps#90]
Hey Team,

I've been getting CPS errors when trying to use `@CompileStatic` at the class level. When I move the attribute to each method, the transformation succeeds.

[Example Class](https://github.com/crichmond1989/testit/blob/master/src/testit/TestRunResult.groovy)

I'd like to add `@CompileStatic` to all compatible classes, but it's a bit inconvenient to add the attribute to every method. Especially my Unit Test classes.

Let me know if I'm using this incorrectly, or if it's not worth using on a CPS transformed class.

**Comment by dwnusbaum** [comment]
I am closing this, but I filed [JENKINS-70018](https://issues.jenkins.io/browse/JENKINS-70018) to track it against Pipeline: Groovy Plugin.
